use_frameworks!

target 'DALI_Example' do
  pod 'DALI', :path => '../'

  target 'DALI_Tests' do
	inherit! :search_paths
	pod 'SwiftyJSON'
	pod 'Socket.IO-Client-Swift'

    pod 'Quick'
    pod 'Nimble'
	
	
	post_install do |installer|
		installer.pods_project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['SWIFT_VERSION'] = '4.0'
			end
		end
	end
  end
end
