# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
# cache: cocoapods
podfile: Example/Podfile
xcode_project: Example/DALI.xcodeproj # path to your xcodeproj folder
xcode_scheme: Example/DALI.xcworkspace
